<?php


$sortTypes = array(
  'date_new_old' => __('Neweffffst', 'mpvc'),
  'date_old_new' => __('Olders', 'mpvc'),
  'price_high_low' => __('Price (High to Low)', 'mpvc'),
  'price_low_high' => __('Price (Low to high)', 'mpvc'),
);


$filterTypes =  array(
  'for-sale' => __('Properties for sale', 'mpvc'),
  'short-term' => __('Vacational rentals', 'mpvc'),
  'long-term' => __('Long term rentals', 'mpvc'),
);

$propertyTypesResidential =  array(
    'apartment'     => __('Apartment', 'mpvc'),
    'country-house' => __('Country House / Finca', 'mpvc'),
    'penthouse'     => __('Penthouse', 'mpvc'),
    'plot'          => __('Plot', 'mpvc'),
    'townhouse'     => __('Townhouse', 'mpvc'),
    'villa'         => __('Villa', 'mpvc'),
);

$propertyTypesComercial =  array(
  'office' => __('Office', 'mpvc'),
  'business' => __('Business', 'mpvc'),
  'cafe' => __('Cafe', 'mpvc'),
  'bar' => __('Bar', 'mpvc'),
  'restaurant' => __('Restaurant', 'mpvc'),
  'retail' => __('Retail', 'mpvc'),
  'shop' => __('Shop', 'mpvc'),
  'hotel' => __('Hotel', 'mpvc'),
  'leisure' => __('Leisure Property', 'mpvc'),
  'industrial' => __('Industrial Property', 'mpvc'),
  'warehouse' => __('Warehouse', 'mpvc'),
  'commercial-land' => __('Landv', 'mpvc'),
  'development' => __('Development', 'mpvc'),
);

$orientationArr =  array(
    'east'       => __('East', 'mpvc'),
    'north'      => __('North', 'mpvc'),
    'north-east' => __('NorthEast', 'mpvc'),
    'north-west' => __('North West', 'mpvc'),
    'south'      => __('South', 'mpvc'),
    'south-east' => __('South East', 'mpvc'),
    'south-west' => __('SouthWest', 'mpvc'),
    'west'       => __('West', 'mpvc'),
);

$featuresArr =  array(
    '24-hour-security'              => __('24 Hour Security', 'mpvc'),
    'air-conditioning'              => __('Air Conditioning', 'mpvc'),
    'alarm-system'                  => __('Alarm System', 'mpvc'),
    'beachside'                     => __('Beachside', 'mpvc'),
    'close-to-park'                 => __('Close to Park', 'mpvc'),
    'close-to-schools'              => __('Close to Schools', 'mpvc'),
    'double-glazing'                => __('Double Glazing', 'mpvc'),
    'fireplace'                     => __('Fireplace', 'mpvc'),
    'frontline-beach'               => __('Frontline Beach', 'mpvc'),
    'frontline-golf'                => __('Frontline Golf', 'mpvc'),
    'gated-complex'                 => __('Gated Complex', 'mpvc'),
    'heated-swimming-pool'          => __('Heated Swimming Pool', 'mpvc'),
    'heating'                       => __('Heating', 'mpvc'),
    'lift'                          => __('Lift', 'mpvc'),
    'modern'                        => __('Modern Style', 'mpvc'),
    'mountain-views'                => __('Mountain Views', 'mpvc'),
    'newly-built'                   => __('Newly Built. Property never lived in.', 'mpvc'),
    'park-views'                    => __('Park Views', 'mpvc'),
    'pool-views'                    => __('Pool Views', 'mpvc'),
    'private-garden'                => __('Private Garden', 'mpvc'),
    'renovation-required'           => __('Renovation Required', 'mpvc'),
    'rustic'                        => __('Rustic Style', 'mpvc'),
    'sauna'                         => __('Sauna', 'mpvc'),
    'sea-views'                     => __('Sea Views', 'mpvc'),
    'solar-power'                   => __('Solar Power', 'mpvc'),
    'storage-room'                  => __('Storage Room', 'mpvc'),
    'swimming-pool'                 => __('Swimming Pool', 'mpvc'),
    'tennis-paddle-court'           => __('Tennis and/or Paddle Court', 'mpvc'),
    'underfloor-heating'            => __('Underfloor Heating', 'mpvc'),
    'golf-views'                    => __('Golf views', 'mpvc'),
    'gym'                           => __('Gimnasium', 'mpvc'),
    'walking-distance-to-amenities' => __('Walking Distance to Amenities', 'mpvc'),
    'walking-distance-to-beach'     => __('Walking Distance to the Beach', 'mpvc'),

);
$provincesArr =  array(
    'C'  => __('A Coruña', 'mpvc'),
    'VI' => __('Álava', 'mpvc'),
    'AB' => __('Albacete', 'mpvc'),
    'A'  => __('Alicante', 'mpvc'),
    'AL' => __('Almería', 'mpvc'),
    'O'  => __('Asturias', 'mpvc'),
    'AV' => __('Ávila', 'mpvc'),
    'BA' => __('Badajoz', 'mpvc'),
    'PM' => __('Balears', 'mpvc'),
    'B'  => __('Barcelona', 'mpvc'),
    'BU' => __('Burgos', 'mpvc'),
    'CC' => __('Cáceres', 'mpvc'),
    'CA' => __('Cádiz', 'mpvc'),
    'S'  => __('Cantabria', 'mpvc'),
    'CS' => __('Castellón', 'mpvc'),
    'EA' => __('Ceuta, Melilla', 'mpvc'),
    'CR' => __('Ciudad Real', 'mpvc'),
    'CO' => __('Córdoba', 'mpvc'),
    'CU' => __('Cuenca', 'mpvc'),
    'GI' => __('Girona', 'mpvc'),
    'GR' => __('Granada', 'mpvc'),
    'GU' => __('Guadalajara', 'mpvc'),
    'SS' => __('Guipúzcoa', 'mpvc'),
    'H'  => __('Huelva', 'mpvc'),
    'HU' => __('Huesca', 'mpvc'),
    'J'  => __('Jaén', 'mpvc'),
    'LO' => __('La Rioja', 'mpvc'),
    'GC' => __('Las Palmas', 'mpvc'),
    'LE' => __('León', 'mpvc'),
    'L'  => __('Lleida', 'mpvc'),
    'LU' => __('Lugo', 'mpvc'),
    'M'  => __('Madrid', 'mpvc'),
    'MA' => __('Málaga', 'mpvc'),
    'MU' => __('Murcia', 'mpvc'),
    'NA' => __('Navarra', 'mpvc'),
    'OR' => __('Ourense', 'mpvc'),
    'P'  => __('Palencia', 'mpvc'),
    'PO' => __('Pontevedra', 'mpvc'),
    'SA' => __('Salamanca', 'mpvc'),
    'TF' => __('Santa Cruz de Tenerife', 'mpvc'),
    'SG' => __('Segovia', 'mpvc'),
    'SE' => __('Sevilla', 'mpvc'),
    'SO' => __('Soria', 'mpvc'),
    'T'  => __('Tarragona', 'mpvc'),
    'TE' => __('Teruel', 'mpvc'),
    'TO' => __('Toledo', 'mpvc'),
    'V'  => __('Valencia', 'mpvc'),
    'VA' => __('Valladolid', 'mpvc'),
    'BI' => __('Vizcaya', 'mpvc'),
    'ZA' => __('Zamora', 'mpvc'),
    'Z'  => __('Zaragoza', 'mpvc'),

);

$langsArray = array(
  'ar' => __('Arabic', 'mpvc'),
  'da' => __('Danish', 'mpvc'),
  'nl' => __('Dutch', 'mpvc'),
  'en' => __('English', 'mpvc'),
  'et' => __('Estonian', 'mpvc'),
  'fi' => __('Finnish', 'mpvc'),
  'fr' => __('French', 'mpvc'),
  'de' => __('German', 'mpvc'),
  'hu' => __('Hungarian', 'mpvc'),
  'it' => __('Italian', 'mpvc'),
  'lt' => __('Lithuanian', 'mpvc'),
  'no' => __('Norwegian', 'mpvc'),
  'pl' => __('Polish', 'mpvc'),
  'pt' => __('Portuguese', 'mpvc'),
  'ru' => __('Russian', 'mpvc'),
  'es' => __('Spanish', 'mpvc'),
  'sv' => __('Swedish', 'mpvc'),
);
