<?php


$sortTypes = array(
  'date_new_old' => __('Newest', IPE_KEY),
  'date_old_new' => __('Olders', IPE_KEY),
  'price_high_low' => __('Price (High to Low)', IPE_KEY),
  'price_low_high' => __('Price (Low to high)', IPE_KEY),
);


$filterTypes =  array(
  'for-sale' => __('Properties for sale', IPE_KEY),
  'short-term' => __('Vacational rentals', IPE_KEY),
  'long-term' => __('Long term rentals', IPE_KEY),
);

$propertyTypesResidential =  array(
    'apartment'     => __('Apartment', IPE_KEY),
    'country-house' => __('Country House / Finca', IPE_KEY),
    'penthouse'     => __('Penthouse', IPE_KEY),
    'plot'          => __('Plot', IPE_KEY),
    'townhouse'     => __('Townhouse', IPE_KEY),
    'villa'         => __('Villa', IPE_KEY),
);

$propertyTypesComercial =  array(
  'office' => __('Office', IPE_KEY),
  'business' => __('Business', IPE_KEY),
  'cafe' => __('Cafe', IPE_KEY),
  'bar' => __('Bar', IPE_KEY),
  'restaurant' => __('Restaurant', IPE_KEY),
  'retail' => __('Retail', IPE_KEY),
  'shop' => __('Shop', IPE_KEY),
  'hotel' => __('Hotel', IPE_KEY),
  'leisure' => __('Leisure Property', IPE_KEY),
  'industrial' => __('Industrial Property', IPE_KEY),
  'warehouse' => __('Warehouse', IPE_KEY),
  'commercial-land' => __('Landv', IPE_KEY),
  'development' => __('Development', IPE_KEY),
);

$orientationArr =  array(
    'east'       => __('East', IPE_KEY),
    'north'      => __('North', IPE_KEY),
    'north-east' => __('NorthEast', IPE_KEY),
    'north-west' => __('North West', IPE_KEY),
    'south'      => __('South', IPE_KEY),
    'south-east' => __('South East', IPE_KEY),
    'south-west' => __('SouthWest', IPE_KEY),
    'west'       => __('West', IPE_KEY),
);

$featuresArr =  array(
    '24-hour-security'              => __('24 Hour Security', IPE_KEY),
    'air-conditioning'              => __('Air Conditioning', IPE_KEY),
    'alarm-system'                  => __('Alarm System', IPE_KEY),
    'beachside'                     => __('Beachside', IPE_KEY),
    'close-to-park'                 => __('Close to Park', IPE_KEY),
    'close-to-schools'              => __('Close to Schools', IPE_KEY),
    'double-glazing'                => __('Double Glazing', IPE_KEY),
    'fireplace'                     => __('Fireplace', IPE_KEY),
    'frontline-beach'               => __('Frontline Beach', IPE_KEY),
    'frontline-golf'                => __('Frontline Golf', IPE_KEY),
    'gated-complex'                 => __('Gated Complex', IPE_KEY),
    'heated-swimming-pool'          => __('Heated Swimming Pool', IPE_KEY),
    'heating'                       => __('Heating', IPE_KEY),
    'lift'                          => __('Lift', IPE_KEY),
    'modern'                        => __('Modern Style', IPE_KEY),
    'mountain-views'                => __('Mountain Views', IPE_KEY),
    'newly-built'                   => __('Newly Built. Property never lived in.', IPE_KEY),
    'park-views'                    => __('Park Views', IPE_KEY),
    'pool-views'                    => __('Pool Views', IPE_KEY),
    'private-garden'                => __('Private Garden', IPE_KEY),
    'renovation-required'           => __('Renovation Required', IPE_KEY),
    'rustic'                        => __('Rustic Style', IPE_KEY),
    'sauna'                         => __('Sauna', IPE_KEY),
    'sea-views'                     => __('Sea Views', IPE_KEY),
    'solar-power'                   => __('Solar Power', IPE_KEY),
    'storage-room'                  => __('Storage Room', IPE_KEY),
    'swimming-pool'                 => __('Swimming Pool', IPE_KEY),
    'tennis-paddle-court'           => __('Tennis and/or Paddle Court', IPE_KEY),
    'underfloor-heating'            => __('Underfloor Heating', IPE_KEY),
    'golf-views'                    => __('Golf views', IPE_KEY),
    'gym'                           => __('Gimnasium', IPE_KEY),
    'walking-distance-to-amenities' => __('Walking Distance to Amenities', IPE_KEY),
    'walking-distance-to-beach'     => __('Walking Distance to the Beach', IPE_KEY),

);
$provincesArr =  array(
    'C'  => __('A Coruña', IPE_KEY),
    'VI' => __('Álava', IPE_KEY),
    'AB' => __('Albacete', IPE_KEY),
    'A'  => __('Alicante', IPE_KEY),
    'AL' => __('Almería', IPE_KEY),
    'O'  => __('Asturias', IPE_KEY),
    'AV' => __('Ávila', IPE_KEY),
    'BA' => __('Badajoz', IPE_KEY),
    'PM' => __('Balears', IPE_KEY),
    'B'  => __('Barcelona', IPE_KEY),
    'BU' => __('Burgos', IPE_KEY),
    'CC' => __('Cáceres', IPE_KEY),
    'CA' => __('Cádiz', IPE_KEY),
    'S'  => __('Cantabria', IPE_KEY),
    'CS' => __('Castellón', IPE_KEY),
    'EA' => __('Ceuta, Melilla', IPE_KEY),
    'CR' => __('Ciudad Real', IPE_KEY),
    'CO' => __('Córdoba', IPE_KEY),
    'CU' => __('Cuenca', IPE_KEY),
    'GI' => __('Girona', IPE_KEY),
    'GR' => __('Granada', IPE_KEY),
    'GU' => __('Guadalajara', IPE_KEY),
    'SS' => __('Guipúzcoa', IPE_KEY),
    'H'  => __('Huelva', IPE_KEY),
    'HU' => __('Huesca', IPE_KEY),
    'J'  => __('Jaén', IPE_KEY),
    'LO' => __('La Rioja', IPE_KEY),
    'GC' => __('Las Palmas', IPE_KEY),
    'LE' => __('León', IPE_KEY),
    'L'  => __('Lleida', IPE_KEY),
    'LU' => __('Lugo', IPE_KEY),
    'M'  => __('Madrid', IPE_KEY),
    'MA' => __('Málaga', IPE_KEY),
    'MU' => __('Murcia', IPE_KEY),
    'NA' => __('Navarra', IPE_KEY),
    'OR' => __('Ourense', IPE_KEY),
    'P'  => __('Palencia', IPE_KEY),
    'PO' => __('Pontevedra', IPE_KEY),
    'SA' => __('Salamanca', IPE_KEY),
    'TF' => __('Santa Cruz de Tenerife', IPE_KEY),
    'SG' => __('Segovia', IPE_KEY),
    'SE' => __('Sevilla', IPE_KEY),
    'SO' => __('Soria', IPE_KEY),
    'T'  => __('Tarragona', IPE_KEY),
    'TE' => __('Teruel', IPE_KEY),
    'TO' => __('Toledo', IPE_KEY),
    'V'  => __('Valencia', IPE_KEY),
    'VA' => __('Valladolid', IPE_KEY),
    'BI' => __('Vizcaya', IPE_KEY),
    'ZA' => __('Zamora', IPE_KEY),
    'Z'  => __('Zaragoza', IPE_KEY),

);

$langsArray = array(
  'ar' => __('Arabic', IPE_KEY),
  'da' => __('Danish', IPE_KEY),
  'nl' => __('Dutch', IPE_KEY),
  'en' => __('English', IPE_KEY),
  'et' => __('Estonian', IPE_KEY),
  'fi' => __('Finnish', IPE_KEY),
  'fr' => __('French', IPE_KEY),
  'de' => __('German', IPE_KEY),
  'hu' => __('Hungarian', IPE_KEY),
  'it' => __('Italian', IPE_KEY),
  'lt' => __('Lithuanian', IPE_KEY),
  'no' => __('Norwegian', IPE_KEY),
  'pl' => __('Polish', IPE_KEY),
  'pt' => __('Portuguese', IPE_KEY),
  'ru' => __('Russian', IPE_KEY),
  'es' => __('Spanish', IPE_KEY),
  'sv' => __('Swedish', IPE_KEY),
);
